Repository jeongm-in/webmark, pull requests merged in 2019-06, with the labels that each got.

#7 Update README.md close #5
  README.md
Labels: documentation

#8 Refactor buttons close #3
  package-lock.json
  package.json
  public/index.html
  src/components/Popup.tsx
  src/components/PopupButton.tsx
  src/index.tsx
Labels: refactoring

#19 Remove unnecessary tags
  package-lock.json
  public/index.html
Labels: enhancement

#18 Load and save skeleton
  package-lock.json
  package.json
  public/manifest.json
  src/index.tsx
Labels: enhancement

#31 Refactorings and bug fixes
  .gitignore
  src/index.tsx
Labels: bug, refactoring
