Repository jeongm-in/webmark, pull requests merged in 2019-07, with the labels that each got.

#37 Implement load functions
  src/index.tsx
Labels: enhancement

#52 Notifications and refactorings
  public/manifest.json
  src/components/Popup.tsx
  src/constants.tsx
  src/index.tsx
Labels: bug, enhancement, refactoring

#57 I18 and bug fixes
  public/_locales/en/messages.json
  public/_locales/ko/messages.json
  public/manifest.json
  src/components/Popup.tsx
  src/components/PopupButton.tsx
  src/constants.tsx
  src/index.tsx
Labels: bug, enhancement, refactoring

#61 Add guard statements
  src/index.tsx
Labels: refactoring

#69 Create background script
  package-lock.json
  package.json
  public/manifest.json
  src/background.ts
  src/constants.ts
  src/index.tsx
  src/utils.ts
  tsconfig.other.json
  webpack.config.js
Labels: enhancement, refactoring

#77 Add options page
  package-lock.json
  package.json
  public/_locales/en/messages.json
  public/_locales/ko/messages.json
  public/images/128.png
  public/images/GitHub-Mark-64px.png
  public/images/promo.png
  public/index.html
  public/manifest.json
  public/options.html
  src/Option.tsx
  src/components/Card.tsx
  src/components/CardAbout.tsx
  src/components/CardGeneralSettings.tsx
  src/components/GithubIcon.tsx
  src/components/LinkItem.tsx
  src/components/OptionEntry.tsx
  src/components/OptionPage.tsx
  src/components/OptionToggle.tsx
  src/constants.ts
  tsconfig.other.json
  webpack.config.js
Labels: enhancement

#93 Prepare first release
  public/_locales/en/detailed_description.txt
  public/_locales/en/screenshot1280x800.png
  public/_locales/ko/detailed_description.txt
  public/_locales/ko/screenshot1280x800.png
  public/favicon.ico
  public/images/GitHub-Mark-64px.png
  public/images/default.png
  public/manifest.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/Option.tsx
  src/background.ts
  src/components/Popup.tsx
  src/constants.ts
  src/index.css
  src/index.tsx
  src/serviceWorker.ts
  src/utils.ts
Labels: refactoring

#98 Refactorings before release
  public/_locales/en/messages.json
  public/_locales/ko/messages.json
  public/manifest.json
  src/Option.tsx
  src/background.ts
  src/utils.ts
Labels: enhancement

#102 First hot fix
  public/_locales/en/detailed_description.txt
  public/_locales/ko/detailed_description.txt
  public/manifest.json
  src/constants.ts
Labels: documentation

#105 Security patch and version 1.0.2
  public/manifest.json
Labels: dependencies

#108 Update documentation
  README.md
Labels: documentation

#109 First tests
  globals.d.ts
  jest.config.js
  package-lock.json
  package.json
  src/__test__/events.test.js
  src/__test__/events.test.ts
  src/__test__/foo.test.ts
  src/__test__/navigate.test.js
  src/__test__/navigate.test.ts
  src/__test__/setupTests.js
  src/__test__/utils.test.ts
  src/events.js
  src/events.ts
  src/foo.ts
  src/navigate.js
  src/navigate.ts
  src/utils.ts
  tsconfig.json
Labels: enhancement

#120 Add MIT license for the repository close #119
  LICENSE.md
Labels: documentation
